# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'iOSDropDown'

  # Pods for GroupMaker

  target 'GroupMakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupMakerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
